version: 0.0
os: linux
files:
  - source: /
    destination: /webapps/chess
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: stop.sh
  ApplicationStart:
    - location: start.sh
